# 开发环境 开启 swagger
swagger:
  enable: true
logging:
  config: classpath:logback-spring.xml
  level:
    com.sl.practice.mapper.base: DEBUG
    io.swagger.models.parameters.AbstractSerializableParameter: error

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_control?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: Root$123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    # joda 开源时间项目 日期格式化
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    #设置空如何序列化
    defaultPropertyInclusion: NON_EMPTY
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    parser:
      #允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      #允许出现单引号
      allow_single_quotes: true
     #设置时间不输出为时间戳

    serialization:
      write-dates-as-timestamps: false
      #格式化输出
      indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: false
mybatis:
  mapper-locations: classpath:mybatis/mapper/uc/base/*.xml
  type-aliases-package: com.sl.practice.enitity.base

request:
  print:
    #打印请求日志记录
    log: true
    #打印响应结果(大json响应体)
    result: true